# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ecommerce.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ecommerce.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65\x63ommerce.proto\x12\tecommerce\"I\n\x12\x43reateOrderRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproduct_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"7\n\x13\x43reateOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"2\n\x0ePaymentRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\":\n\x0fPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t2\\\n\x0cOrderService\x12L\n\x0b\x43reateOrder\x12\x1d.ecommerce.CreateOrderRequest\x1a\x1e.ecommerce.CreateOrderResponse2Y\n\x0ePaymentService\x12G\n\x0eProcessPayment\x12\x19.ecommerce.PaymentRequest\x1a\x1a.ecommerce.PaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ecommerce_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEORDERREQUEST']._serialized_start=30
  _globals['_CREATEORDERREQUEST']._serialized_end=103
  _globals['_CREATEORDERRESPONSE']._serialized_start=105
  _globals['_CREATEORDERRESPONSE']._serialized_end=160
  _globals['_PAYMENTREQUEST']._serialized_start=162
  _globals['_PAYMENTREQUEST']._serialized_end=212
  _globals['_PAYMENTRESPONSE']._serialized_start=214
  _globals['_PAYMENTRESPONSE']._serialized_end=272
  _globals['_ORDERSERVICE']._serialized_start=274
  _globals['_ORDERSERVICE']._serialized_end=366
  _globals['_PAYMENTSERVICE']._serialized_start=368
  _globals['_PAYMENTSERVICE']._serialized_end=457
# @@protoc_insertion_point(module_scope)
