version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  payment_service:
    build: ./payment_service
    container_name: payment_service
    ports:
      - "50052:50052" # Porta gRPC do serviço de pagamentos
    volumes:
      - ./protos:/app/protos

  order_service:
    build: ./order_service
    container_name: order_service
    ports:
      - "50051:50051" # Porta gRPC do serviço de encomendas
    volumes:
      - ./protos:/app/protos
    depends_on:
      - rabbitmq
      - payment_service

  notification_service:
    build: ./notification_service
    container_name: notification_service
    volumes:
      - ./protos:/app/protos
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
    driver: local
